import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import Banner from "src/components/Banner";
import Header from "src/components/Header";
import ProductFeed from "src/components/ProductFeed";
import { ProductsInterface } from "src/types/interface";

interface HomeProps {
  products: ProductsInterface[];
}

const Home: NextPage<HomeProps> = ({ products }: HomeProps) => {
  return (
    <div className="bg-gray-100">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="max-w-screen-2xl mx-auto">
        <Banner />
        <ProductFeed products={products} />
      </main>
    </div>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async () => {
  const products = await fetch("https://fakestoreapi.com/products").then(
    (res) => res.json()
  );

  return {
    props: {
      products,
    },
  };
};
