import type { NextPage } from "next";
import Head from "next/head";
import Banner from "src/components/Banner";
import Header from "src/components/Header";

const Home: NextPage = () => {
  return (
    <div className="bg-gray-100">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="max-w-screen-2xl mx-auto">
        <Banner />
      </main>
    </div>
  );
};

export default Home;
